name: Publish documentation
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run doc && touch docs/.nojekyll
      - uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: 'docs/'
          GH_PAT: ${{ secrets.GH_PAT }}
